config/routes.rb
Rails.application.routes.draw do

  resources :friendships do
    post :process_friendship_request
  end

  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations" }
  resources :challenges do
    get :my_challenges, :on => :collection

  end
  devise_scope :user do
    root to: "devise/sessions#new"
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :users do
    get :dashboard
  end

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class_name => "User"

  scope :confirmed, -> { where(status: "Accepted") }
  scope :unconfirmed, -> { where(:status => "RequestSent") }
  scope :pending_received_friend_requests, ->(friend_id) { where(:friend_id => friend_id, :status => "RequestSent") }
  #scope :pending_sent_friend_requests, -> { where(:status => "RequestSent") }
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :set_friendship, only: [:show, :edit, :update, :destroy, :process_friendship_request]

  respond_to :html

  def index
    @friendships = current_user.friendships
    respond_with(@friendships)
  end

  def show
    respond_with(@friendship)
  end

  def new
    @friendship = Friendship.new
    respond_with(@friendship)
  end

  def edit
  end

  def create
    @friendship = Friendship.new(friendship_params)
    flash[:notice] = 'Friendship was successfully created.' if @friendship.save
    respond_with(@friendship)
  end

  def update
    flash[:notice] = 'Friendship was successfully updated.' if @friendship.update(friendship_params)
    respond_with(@friendship)
  end

  def destroy
    @friendship.destroy
    respond_with(@friendship)
  end

  # action to process friendship requests
  def process_friendship_request
     if params["process"] == "accept"
       #@friendship.update(:status => "Accepted")
       flash[:notice => "Friendship Request accepted"]
     elsif params["process"] == "reject"
       #@friendship.update(:status => "Rejected")
       flash[:notice => "Friendship Request rejected"]
     end
    respond_to do |format|
      format.js
    end
  end

  private
    def set_friendship
      @friendship = Friendship.find(params[:id] || params[:friendship_id])
    end

    def friendship_params
      params.require(:friendship).permit(:user_id, :friend_id, :status)
    end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_form.html.erb
<%= form_for(@friendship) do |f| %>
  <% if @friendship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
      <% @friendship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :friend_id %><br>
    <%= f.number_field :friend_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friendships/edit.html.erb
<h1>Editing friendship</h1>

<%= render 'form' %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<!-- <h1>Listing friendships</h1>

 <table>
  <thead>
    <tr>
      <th>User</th>
      <th>Friend</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friendships.each do |friendship| %>
      <tr>
        <td><%= friendship.user_id %></td>
        <td><%= friendship.friend_id %></td>
        <td><%= friendship.status %></td>
        <td><%= link_to 'Show', friendship %></td>
        <td><%= link_to 'Edit', edit_friendship_path(friendship) %></td>
        <td><%= link_to 'Destroy', friendship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friendship', new_friendship_path %> -->

<div class="panel panel-grey">
  <div class="panel-heading">Listing friends</div>
  <div class="panel-body">
    <table class="table table-hover-color">
      <thead>
        <tr>
          <th>ID</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <% @friendships.each do |friendship| %>
        <tr class="<%= cycle("active", "success", "warning", "danger") -%>">
          <td><%= friendship.friend_id %></td>
          <td><%= friendship.status %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/friendships/new.html.erb
<h1>New friendship</h1>

<%= render 'form' %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/process_friendship_request.js.erb
//$("#<%= @friendship.id %>").hide();
//alert(<%= params['process'] %>);
$("#process_fr" + <%= @friendship.id %>).hide();

app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @friendship.user_id %>
</p>

<p>
  <strong>Friend:</strong>
  <%= @friendship.friend_id %>
</p>

<p>
  <strong>Status:</strong>
  <%= @friendship.status %>
</p>

<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>