config/routes.rb
Rails.application.routes.draw do

  resources :friendships do
    post :process_friendship_request
  end

  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations" }
  resources :challenges do
    get :my_challenges, :on => :collection

  end
  devise_scope :user do
    root to: "devise/sessions#new"
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :users do
    get :dashboard
  end

end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
  resourcify

  dragonfly_accessor :image
  attr_accessor :c_start , :c_end


  #get owners of a challenge
  def get_owners
    self.roles.where(:name => "owner").first.users
  end

  #to check if a user is an owner of a challenge or not
  def is_owner?(user)
    self.get_owners.include?(user)
  end

end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :set_challenge, only: [:show, :edit, :update, :destroy]

  # GET /challenges
  # GET /challenges.json
  def index
    @challenges = Challenge.all
  end

  # GET /challenges/1
  # GET /challenges/1.json
  def show
  end

  # GET /challenges/new
  def new
    @challenge = Challenge.new
  end

  # GET /challenges/1/edit
  def edit
  end

  # POST /challenges
  # POST /challenges.json
  def create
    @start = params[:challenge][:c_start].to_datetime
    @end = params[:challenge][:c_end].to_datetime
    params[:challenge]["starts_on(1i)"] = @start.year.to_s
    params[:challenge]["starts_on(2i)"] = @start.month.to_s
    params[:challenge]["starts_on(3i)"] = @start.day.to_s
    params[:challenge]["starts_on(4i)"] = @start.hour.to_s
    params[:challenge]["starts_on(5i)"] = @start.min.to_s

    params[:challenge]["ends_on(1i)"] = @end.year.to_s
    params[:challenge]["ends_on(2i)"] = @end.month.to_s
    params[:challenge]["ends_on(3i)"] = @end.day.to_s
    params[:challenge]["ends_on(4i)"] = @end.hour.to_s
    params[:challenge]["ends_on(5i)"] = @end.min.to_s

    @challenge = Challenge.new(challenge_params)

    respond_to do |format|
      if @challenge.save
        current_user.add_role :owner, @challenge
        format.html { redirect_to @challenge, notice: 'Challenge was successfully created.' }
        format.json { render :show, status: :created, location: @challenge }
      else
        format.html { render :new }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /challenges/1
  # PATCH/PUT /challenges/1.json
  def update
    respond_to do |format|
      if @challenge.update(challenge_params)
        format.html { redirect_to @challenge, notice: 'Challenge was successfully updated.' }
        format.json { render :show, status: :ok, location: @challenge }
      else
        format.html { render :edit }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /challenges/1
  # DELETE /challenges/1.json
  def destroy
    @challenge.destroy
    respond_to do |format|
      format.html { redirect_to challenges_url, notice: 'Challenge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #get challenges created by current_user

  def my_challenges
    @my_challenges = Challenge.with_role(:owner, current_user)
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_challenge
      @challenge = Challenge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def challenge_params
      params.require(:challenge).permit(:name, :description, :starts_on, :ends_on,:image , :c_start , :c_end)
    end
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/challenges/_form.html.erb
<div class="box box-success">
  <div class="box-header">
    <h3 class="box-title">Create Challenge</h3></div>

      <%= form_for(@challenge, {:role => "form"}) do |f| %>
      <div class="box-body">
        <% if @challenge.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@challenge.errors.count, "error") %> prohibited this challenge from being saved:</h2>

            <ul>
            <% @challenge.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>



            <div class="form-group">
              <div class="row">
                <div class="col-sm-1">
                  <%= f.label :name, :class => "control-label" %>
                </div>
                <div class="col-sm-7">
                  <%= f.text_field :name ,:class =>"form-control"%>
                </div>
              </div>
            </div>



            <div class="form-group">
              <div class="row">
                <div class="col-sm-1">
                  <%= f.label :description, :class => "control-label" %>
                </div>
                <div class="col-sm-7">
                  <%= f.text_area :description ,:class =>"form-control"%>
                </div>
              </div>
            </div>

            <div class="form-group">
              <div class="row">
                <div class="col-sm-1">
                  <%= f.label :starts_on, :class => "control-label" %>
                </div>
                <div class="col-sm-7">
                  <div style="display:none">
                    <%= f.datetime_select :starts_on ,:class => 'datetimepicker' %>
                  </div>
                  <%= f.text_field :c_start, :class => "datetimepicker",:id => "c_start"  %>
                </div>
              </div>
            </div>

            <div class="form-group">
              <div class="row">
                <div class="col-sm-1">
                  <%= f.label :ends_on, :class => "control-label" %>
                </div>
                <div class="col-sm-7">
                  <div style="display:none">
                    <%= f.datetime_select :ends_on %>
                  </div>
                  <%= f.text_field :c_end, :class => "datetimepicker",:id => "c_end"  %>
                </div>
              </div>
            </div>

            <div class="form-group">
              <div class="row">
                <div class="col-sm-1">
                  <%= f.label :image, :class => "control-label" %>
                </div>
                <div class="col-sm-7">
                  <%= f.file_field :image %>
                </div>
              </div>
            </div>




  </div>
        <div class="box-footer">
          <%= f.submit :class => "btn btn-primary" %>
          </div>
      <% end %>

</div>





<div class="box box-primary">
  <div class="box-header">
    <h3 class="box-title">Quick Example</h3>
  </div><!-- /.box-header -->
  <!-- form start -->
  <form role="form">
    <div class="box-body">
      <div class="form-group">
        <label for="exampleInputEmail1">Email address</label>
        <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
      </div>
      <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
      </div>
      <div class="form-group">
        <label for="exampleInputFile">File input</label>
        <input type="file" id="exampleInputFile">
        <p class="help-block">Example block-level help text here.</p>
      </div>
      <div class="checkbox">
        <label>
          <input type="checkbox"> Check me out
        </label>
      </div>
    </div><!-- /.box-body -->

    <div class="box-footer">
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </form>
</div>

app/views/challenges/edit.html.erb
<h1>Editing challenge</h1>

<%= render 'form' %>

<%= link_to 'Show', @challenge %> |
<%= link_to 'Back', challenges_path %>

app/views/challenges/index.html.erb
<h2>Listing challenges</h2>

<div class="box box-success">
  <div class="box-header">
    <h3 class="box-title">Listing challenges</h3>
    <!-- <div class="box-tools">
      <div class="input-group">
        <input type="text" name="table_search" class="form-control input-sm pull-right" style="width: 150px;" placeholder="Search">
        <div class="input-group-btn">
          <button class="btn btn-sm btn-default"><i class="fa fa-search"></i></button>
        </div>
      </div>
    </div> -->
  </div><!-- /.box-header -->
  <div class="box-body table-responsive no-padding">
    <table class="table table-hover">
      <tbody><tr>
        <th>Name</th>
        <th>Category</th>
        <th>Owner</th>
        <th>Status</th>
      </tr>
      <% @challenges.each do |challenge| %>
      <tr>
        <td><%= challenge.name %></td>
        <td>category</td>
        <td>
          <% challenge.get_owners.each do |owner| %>
          <%= owner.name %>
          <% end %>
        </td>
        <% if challenge.starts_on <= DateTime.now && DateTime.now < challenge.ends_on %>
        <td><span class="label label-success">Active</span></td>
        <% elsif challenge.ends_on < DateTime.now %>
        <td><span class="label label-primary">Over</span></td>
        <% else %>
        <td><span class="label label-info">Not yet Started</span></td>
        <% end %>
      </tr>
      <% end %>
    </tbody></table>
  </div><!-- /.box-body -->
</div>

app/views/challenges/my_challenges.html.erb
<h2>My challenges</h2>

<div class="box box-success">
  <div class="box-header">
    <h3 class="box-title">Listing your challenges</h3>
    <!-- <div class="box-tools">
    <div class="input-group">
    <input type="text" name="table_search" class="form-control input-sm pull-right" style="width: 150px;" placeholder="Search">
    <div class="input-group-btn">
    <button class="btn btn-sm btn-default"><i class="fa fa-search"></i></button>
  </div>
</div>
</div> -->
</div><!-- /.box-header -->
<div class="box-body table-responsive no-padding">
  <table class="table table-hover">
    <tbody><tr>
      <th>Name</th>
      <th>Category</th>
      <th>Owner</th>
      <th>Status</th>
      <th>View</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
    <% @my_challenges.each do |challenge| %>
    <tr>
      <td><%= challenge.name %></td>
      <td>category</td>
      <td>
        <% challenge.get_owners.each do |owner| %>
        <%= owner.name %>
        <% end %>
      </td>
      <% if challenge.starts_on <= DateTime.now && DateTime.now < challenge.ends_on %>
      <td><span class="label label-success">Active</span></td>
      <% elsif challenge.ends_on < DateTime.now %>
      <td><span class="label label-primary">Over</span></td>
      <% else %>
      <td><span class="label label-info">Not yet Started</span></td>
      <% end %>
      <td>&nbsp;
        <%= link_to "<i class='fa fa-fw fa-eye'></i>".html_safe, challenge_path(challenge) %>
      </td>
      <td>&nbsp;
        <%= link_to "<i class='fa fa-fw fa-edit'></i>".html_safe, edit_challenge_path(challenge) %>
      </td>
      <td>&nbsp;&nbsp;
        <%= link_to "<i class='fa fa-fw fa-trash-o'></i>".html_safe, challenge_path(challenge),method: :delete,:confirm=>'Are you sure?'  %>
      </td>
    </tr>
    <% end %>
  </tbody></table>
</div><!-- /.box-body -->
</div>

<br>

<%= link_to 'New Challenge', new_challenge_path , :class => "btn btn-green navbar-btn"%>

app/views/challenges/new.html.erb
<%= render 'form' %>

app/views/challenges/show.html.erb
<p id="notice"><%= notice %></p>


<div class="col-md-12"><h2><%= @challenge.name %></h2>

  <div class="row mtl">
    <div class="col-md-3">
      <span><h4>Created By </h4></span>
      <div class="form-group">
        <div class="text-center mbl"><img src="<%= get_user_image_url(@challenge.get_owners.first) %>" alt="" class="img-circle" height="120" width="120"> </div>
        <div class="text-center mbl"></div>
      </div>
        <table class="table table-striped table-hover">
          <tbody>
            <tr>
              <td>User Name</td>
              <td><%= current_user.name %></td>
            </tr>
            <tr>
              <td>Email</td>
              <td><%= current_user.email %></td>
            </tr>
            <tr>
              <td>Status</td>
              <td><span class="label label-success">Active</span></td>
            </tr>
            <tr>
              <td>User Rating</td>
              <td><i class="fa fa-star text-yellow fa-fw"></i><i class="fa fa-star text-yellow fa-fw"></i><i class="fa fa-star text-yellow fa-fw"></i><i class="fa fa-star text-yellow fa-fw"></i><i class="fa fa-star text-yellow fa-fw"></i></td>
            </tr>
            <tr>
              <td>Member Since</td>
              <td><%= current_user.created_at.to_datetime.strftime("%B %d, %Y") %></td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="col-md-9">
        <ul class="nav nav-tabs">
          <!-- <li class="active"><a href="#tab-edit" data-toggle="tab">Edit Profile</a></li> -->
        </ul>
        <div id="generalTabContent" class="tab-content">
          <div class="dw_clock" style="zoom: 0.95;"></div>
          <p>
            <%= image_tag @challenge.image.url ,:class => 'img-responsive', :width => '400', :height => "400" if @challenge.image_stored? %>
          </p>
          <p>
            <strong>Name:</strong>
            <%= @challenge.name %>
          </p>
          <p>
            <strong>Description:</strong>
            <%= @challenge.description %>
          </p>
          <p>
            <strong>Starts on:</strong>
            <%= @challenge.starts_on %>
          </p>
          <p>
            <strong>Ends on:</strong>
            <%= @challenge.ends_on %>
          </p>
          <%= link_to 'Edit', edit_challenge_path(@challenge) %> |
          <%= link_to 'Back', challenges_path %>
        </div>
      </div>
    </div>
  </div>